title:        imagettftextblur
name:         imagettftextblur
description:  imagettftextblur is a drop in replacement for imagettftext with added parameters to add blur, glow and shadow effects to your PHP GD images.
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "https://imagettftextblur.agjgd.org"
includes_dir: .
layouts_dir:  documentation/imagettftextblur.agjgd.org/layouts
exclude:      [
               .github,
               .github/ISSUE_TEMPLATE,
               .github/ISSUE_TEMPLATE/00-bug.md,
               .github/ISSUE_TEMPLATE/01-feature.md,
               .github/CODE_OF_CONDUCT.md,
               .github/CODEOWNERS,
               .github/CONTRIBUTING.md,
               .github/FUNDING.yml,
               .github/PULL_REQUEST_TEMPLATE.md,
               .github/SECURITY.md,
               .github/SUPPORT.md,
               CHANGELOG.md,
               CNAME,
               composer.json,
               documentation/README.md,
               examples/*.php,
               examples/*.ttf,
               LICENSE,
               README.md,
               source
              ]
