name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - andrewgjohnson
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g. email@example.com
    validations:
      required: false
  - type: textarea
    id: system-information
    attributes:
      label: What is your system information?
      description: What version of PHP and imagettftextblur are manifesting the issue?
      value: |
        - PHP version:
        - imagettftextblur version:
    validations:
      required: false
  - type: textarea
    id: current-behaviour
    attributes:
      label: Describe the current behaviour
      description: How is the code currently behaving?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Describe the expected behaviour
      description: How should the code be behaving?
      placeholder: Describe the fix
    validations:
      required: true
  - type: textarea
    id: standalone-code
    attributes:
      label: Standalone code to reproduce the issue
      description: How can we reproduce the error with code?
      placeholder: Share the code snippet here
    validations:
      required: false
  - type: textarea
    id: other-information
    attributes:
      label: Any other information
      description: Include any logs or source code that would be helpful to diagnose the problem. Large logs and files should be attached.
      placeholder: Any other information here
    validations:
      required: false
