blank_issues_enabled: false
contact_links:
- name: GitHub Discussions
  url: https://github.com/andrewgjohnson/imagettftextblur/discussions
  about: Discussions and Q&A should go in the discussions area
